// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | ThreeDSlice
  | FaqSlice
  | FeatureSlice
  | ContentSlice
  | BlogSlice
  | BentoGridSlice
  | SectionIntroSlice
  | TestimonialSlice
  | StatsSlice
  | GridListSlice
  | ContactSectionSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice =
  | SectionIntroSlice
  | RichTextSlice
  | HeroSlice
  | FeatureSlice
  | ContactSectionSlice
  | GridListSlice
  | TestimonialSlice
  | StatsSlice
  | BlogSlice
  | ContentSlice
  | FaqSlice
  | BentoGridSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Item in *Settings → Navigation Items*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Work
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /work
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Settings → Footer Sections → Section Links*
 */
export interface SettingsDocumentDataFooterSectionsSectionLinksItem {
  /**
   * Link Text field in *Settings → Footer Sections → Section Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Work
   * - **API ID Path**: settings.footer_sections[].section_links[].link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → Footer Sections → Section Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /work
   * - **API ID Path**: settings.footer_sections[].section_links[].link_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Settings → Footer Sections*
 */
export interface SettingsDocumentDataFooterSectionsItem {
  /**
   * Section Title field in *Settings → Footer Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Work
   * - **API ID Path**: settings.footer_sections[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Links field in *Settings → Footer Sections*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_sections[].section_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  section_links: prismic.NestedGroupField<
    Simplify<SettingsDocumentDataFooterSectionsSectionLinksItem>
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Studio
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Contact Button Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact us
   * - **API ID Path**: settings.contact_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_button_text: prismic.KeyTextField;

  /**
   * Contact Button Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /contact
   * - **API ID Path**: settings.contact_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Navigation Items field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationItem>
  > /**
   * Footer Sections field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_sections[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  footer_sections: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSectionsItem>
  >;

  /**
   * Newsletter Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Newsletter
   * - **API ID Path**: settings.newsletter_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  newsletter_title: prismic.KeyTextField;

  /**
   * Newsletter Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subscribe to get the latest design news, articles, resources and inspiration.
   * - **API ID Path**: settings.newsletter_description
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  newsletter_description: prismic.KeyTextField;

  /**
   * Copyright Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © Studio Agency Inc.
   * - **API ID Path**: settings.copyright_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | PageDocument
  | ProductDocument
  | SettingsDocument;

/**
 * Primary content in *BentoGrid → Default → Primary*
 */
export interface BentoGridSliceDefaultPrimary {
  /**
   * Section Title field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Premium Microphones
   * - **API ID Path**: bento_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Professional Audio
   * - **API ID Path**: bento_grid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Description field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Discover our range of professional-grade microphones...
   * - **API ID Path**: bento_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *BentoGrid → Items*
 */
export interface BentoGridSliceDefaultItem {
  /**
   * Product Title field in *BentoGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: B-6 Pro Microphone
   * - **API ID Path**: bento_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Product Description field in *BentoGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: High-end condenser microphone with...
   * - **API ID Path**: bento_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;

  /**
   * Product Image field in *BentoGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  item_image: prismic.ImageField<"thumbnail">;

  /**
   * Price field in *BentoGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: $2,999
   * - **API ID Path**: bento_grid.items[].item_price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_price: prismic.KeyTextField;

  /**
   * Badge field in *BentoGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New
   * - **API ID Path**: bento_grid.items[].item_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_badge: prismic.KeyTextField;

  /**
   * Product Link field in *BentoGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to product page
   * - **API ID Path**: bento_grid.items[].item_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Grid Size field in *BentoGrid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select grid size
   * - **API ID Path**: bento_grid.items[].item_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  item_size: prismic.SelectField<"small" | "medium" | "large">;
}

/**
 * Default variation for BentoGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default BentoGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoGridSliceDefaultPrimary>,
  Simplify<BentoGridSliceDefaultItem>
>;

/**
 * Slice variation for *BentoGrid*
 */
type BentoGridSliceVariation = BentoGridSliceDefault;

/**
 * BentoGrid Shared Slice
 *
 * - **API ID**: `bento_grid`
 * - **Description**: Bento grid layout for showcasing products with different sized cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSlice = prismic.SharedSlice<
  "bento_grid",
  BentoGridSliceVariation
>;

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Section Title field in *Blog → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Latest Articles
   * - **API ID Path**: blog.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *Blog → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog
   * - **API ID Path**: blog.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Description field in *Blog → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Stay updated with the latest news and insights from the audio world...
   * - **API ID Path**: blog.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * View All Link field in *Blog → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to blog page
   * - **API ID Path**: blog.default.primary.view_all_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_all_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Blog → Items*
 */
export interface BlogSliceDefaultItem {
  /**
   * Post Title field in *Blog → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Future of Professional Audio
   * - **API ID Path**: blog.items[].post_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  post_title: prismic.KeyTextField;

  /**
   * Post Excerpt field in *Blog → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Explore the latest trends and innovations in professional audio technology...
   * - **API ID Path**: blog.items[].post_excerpt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  post_excerpt: prismic.RichTextField;

  /**
   * Post Image field in *Blog → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].post_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  post_image: prismic.ImageField<"thumbnail">;

  /**
   * Post Date field in *Blog → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].post_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  post_date: prismic.DateField;

  /**
   * Category field in *Blog → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Technology
   * - **API ID Path**: blog.items[].post_category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  post_category: prismic.KeyTextField;

  /**
   * Post Link field in *Blog → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to full article
   * - **API ID Path**: blog.items[].post_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  post_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Featured Post field in *Blog → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog.items[].featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Blog Section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  Simplify<BlogSliceDefaultItem>
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog section for showcasing articles and posts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Us
   * - **API ID Path**: contact_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact description...
   * - **API ID Path**: contact_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Email field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contact@example.com
   * - **API ID Path**: contact_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +1 (555) 123-4567
   * - **API ID Path**: contact_section.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: Contact section with title, description, and contact information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *Content → Default → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Section Title field in *Content → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About Our Technology
   * - **API ID Path**: content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *Content → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Innovation
   * - **API ID Path**: content.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Content → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your content here...
   * - **API ID Path**: content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Featured Image field in *Content → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"thumbnail">;

  /**
   * Image Position field in *Content → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select image position
   * - **API ID Path**: content.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"left" | "right" | "top" | "bottom">;

  /**
   * Background Color field in *Content → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select background
   * - **API ID Path**: content.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<"white" | "gray" | "dark">;

  /**
   * Call to Action field in *Content → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional CTA link
   * - **API ID Path**: content.default.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  call_to_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Text field in *Content → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: content.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Content Section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Flexible content section with rich text and media
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *FAQ → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Section Title field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Frequently Asked Questions
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Support
   * - **API ID Path**: faq.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Description field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Find answers to common questions about our microphones...
   * - **API ID Path**: faq.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *FAQ → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *FAQ → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What makes your microphones different?
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our microphones are designed with premium components and advanced technology...
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default FAQ Section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Frequently asked questions section with expandable answers
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Feature → Default → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * Section Title field in *Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Why Choose Our Microphones
   * - **API ID Path**: feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Professional Features
   * - **API ID Path**: feature.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Description field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Discover what makes our microphones stand out...
   * - **API ID Path**: feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Invert Colors field in *Feature → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: feature.default.primary.invert
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  invert: prismic.BooleanField;
}

/**
 * Primary content in *Feature → Items*
 */
export interface FeatureSliceDefaultItem {
  /**
   * Feature Title field in *Feature → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Studio-Grade Quality
   * - **API ID Path**: feature.items[].feature_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feature_title: prismic.KeyTextField;

  /**
   * Feature Description field in *Feature → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Professional audio quality with crystal clear sound...
   * - **API ID Path**: feature.items[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;

  /**
   * Feature Icon field in *Feature → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an icon
   * - **API ID Path**: feature.items[].feature_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  feature_icon: prismic.SelectField<
    | "microphone"
    | "waveform"
    | "settings"
    | "shield"
    | "star"
    | "lightning"
    | "headphones"
    | "volume"
    | "music"
    | "record"
  >;

  /**
   * Feature Link field in *Feature → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional link for more details
   * - **API ID Path**: feature.items[].feature_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  feature_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Feature Section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  Simplify<FeatureSliceDefaultItem>
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature section with icons and descriptions for highlighting product features
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *GridList → Default → Primary*
 */
export interface GridListSliceDefaultPrimary {
  /**
   * Section Title field in *GridList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Grid List Title
   * - **API ID Path**: grid_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Invert Colors field in *GridList → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: grid_list.default.primary.invert
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  invert: prismic.BooleanField;
}

/**
 * Primary content in *GridList → Items*
 */
export interface GridListSliceDefaultItem {
  /**
   * Item Title field in *GridList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Item title
   * - **API ID Path**: grid_list.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *GridList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Item description...
   * - **API ID Path**: grid_list.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Default variation for GridList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default GridList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridListSliceDefaultPrimary>,
  Simplify<GridListSliceDefaultItem>
>;

/**
 * Slice variation for *GridList*
 */
type GridListSliceVariation = GridListSliceDefault;

/**
 * GridList Shared Slice
 *
 * - **API ID**: `grid_list`
 * - **Description**: Grid layout for displaying list items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridListSlice = prismic.SharedSlice<
  "grid_list",
  GridListSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company Name
   * - **API ID Path**: hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page description...
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Centered field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.centered
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  centered: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with eyebrow, title, and description
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SectionIntro → Default → Primary*
 */
export interface SectionIntroSliceDefaultPrimary {
  /**
   * Eyebrow field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Label
   * - **API ID Path**: section_intro.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Title
   * - **API ID Path**: section_intro.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section description...
   * - **API ID Path**: section_intro.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Smaller field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: section_intro.default.primary.smaller
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  smaller: prismic.BooleanField;

  /**
   * Invert field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: section_intro.default.primary.invert
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  invert: prismic.BooleanField;
}

/**
 * Default variation for SectionIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default SectionIntro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionIntro*
 */
type SectionIntroSliceVariation = SectionIntroSliceDefault;

/**
 * SectionIntro Shared Slice
 *
 * - **API ID**: `section_intro`
 * - **Description**: Section introduction with eyebrow, title, and description
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionIntroSlice = prismic.SharedSlice<
  "section_intro",
  SectionIntroSliceVariation
>;

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface StatsSliceDefaultPrimary {
  /**
   * Title field in *Stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Impact
   * - **API ID Path**: stats.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Stats → Items*
 */
export interface StatsSliceDefaultItem {
  /**
   * Stat Label field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Stat label
   * - **API ID Path**: stats.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Stat Value field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 100+
   * - **API ID Path**: stats.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Stats
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsSliceDefaultPrimary>,
  Simplify<StatsSliceDefaultItem>
>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Statistics section with title and stats
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSlice = prismic.SharedSlice<"stats", StatsSliceVariation>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Quote field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Customer testimonial quote...
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Client Name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Client or Company Name
   * - **API ID Path**: testimonial.default.primary.client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Client Logo field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.client_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  client_logo: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Testimonial
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Customer testimonial with quote and client info
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *ThreeD → Default → Primary*
 */
export interface ThreeDSliceDefaultPrimary {
  /**
   * Section Title field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Experience Our Microphones in 3D
   * - **API ID Path**: three_d.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Interactive
   * - **API ID Path**: three_d.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Description field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Explore our microphones in stunning 3D detail...
   * - **API ID Path**: three_d.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * 3D Model File (FBX) field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Upload your FBX file
   * - **API ID Path**: three_d.default.primary.model_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  model_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Animation Type field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select animation style
   * - **API ID Path**: three_d.default.primary.animation_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  animation_type: prismic.SelectField<
    "float" | "rotate_complex" | "wave" | "parallax" | "zoom_rotate" | "spiral"
  >;

  /**
   * Animation Speed field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select speed
   * - **API ID Path**: three_d.default.primary.animation_speed
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  animation_speed: prismic.SelectField<"slow" | "medium" | "fast">;

  /**
   * Background field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select background
   * - **API ID Path**: three_d.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<"transparent" | "dark" | "gradient">;

  /**
   * Lighting Setup field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select lighting
   * - **API ID Path**: three_d.default.primary.lighting
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  lighting: prismic.SelectField<"studio" | "dramatic" | "soft" | "environment">;

  /**
   * Camera Angle field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select camera view
   * - **API ID Path**: three_d.default.primary.camera_angle
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  camera_angle: prismic.SelectField<"front" | "side" | "angle" | "top">;

  /**
   * Enable Auto Rotation field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: three_d.default.primary.enable_auto_rotation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  enable_auto_rotation: prismic.BooleanField;

  /**
   * Scroll Animation Intensity field in *ThreeD → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1.0
   * - **API ID Path**: three_d.default.primary.scroll_intensity
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  scroll_intensity: prismic.NumberField;
}

/**
 * Default variation for ThreeD Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default 3D Model Section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeDSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThreeDSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThreeD*
 */
type ThreeDSliceVariation = ThreeDSliceDefault;

/**
 * ThreeD Shared Slice
 *
 * - **API ID**: `three_d`
 * - **Description**: 3D model display with scroll-based animations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeDSlice = prismic.SharedSlice<"three_d", ThreeDSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterSectionsSectionLinksItem,
      SettingsDocumentDataFooterSectionsItem,
      AllDocumentTypes,
      BentoGridSlice,
      BentoGridSliceDefaultPrimary,
      BentoGridSliceDefaultItem,
      BentoGridSliceVariation,
      BentoGridSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimary,
      BlogSliceDefaultItem,
      BlogSliceVariation,
      BlogSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceDefaultItem,
      FeatureSliceVariation,
      FeatureSliceDefault,
      GridListSlice,
      GridListSliceDefaultPrimary,
      GridListSliceDefaultItem,
      GridListSliceVariation,
      GridListSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SectionIntroSlice,
      SectionIntroSliceDefaultPrimary,
      SectionIntroSliceVariation,
      SectionIntroSliceDefault,
      StatsSlice,
      StatsSliceDefaultPrimary,
      StatsSliceDefaultItem,
      StatsSliceVariation,
      StatsSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      ThreeDSlice,
      ThreeDSliceDefaultPrimary,
      ThreeDSliceVariation,
      ThreeDSliceDefault,
    };
  }
}
