// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accessories: dynamic(() => import("./Accessories")),
  artists: dynamic(() => import("./Artists")),
  bento_grid: dynamic(() => import("./BentoGrid")),
  blog: dynamic(() => import("./Blog")),
  blog_listing: dynamic(() => import("./BlogListing")),
  blog_overview: dynamic(() => import("./BlogOverview")),

  checkout: dynamic(() => import("./Checkout")),
  contact_section: dynamic(() => import("./ContactSection")),
  content: dynamic(() => import("./Content")),


  enhanced_bento_grid: dynamic(() => import("./EnhancedBentoGrid")),
  faq: dynamic(() => import("./FAQ")),
  feature: dynamic(() => import("./Feature")),
  feature_blocks: dynamic(() => import("./FeatureBlocks")),
  foundation: dynamic(() => import("./Foundation")),
  modal_blocks: dynamic(() => import("./ModalBlocks")),

  hero: dynamic(() => import("./Hero")),
  split_feature: dynamic(() => import("./SplitFeature")),
  hero_image: dynamic(() => import("./HeroImage")),
  valve_hero: dynamic(() => import("./valveHero")),
  video_hero: dynamic(() => import("./VideoHero")),


  possibilities: dynamic(() => import("./Possibilities")),
  product: dynamic(() => import("./Product")),

  section_intro: dynamic(() => import("./SectionIntro")),

  stylized_image: dynamic(() => import("./StylizedImage")),
  success: dynamic(() => import("./Success")),
  testimonial: dynamic(() => import("./Testimonial")),
  
  technical_specifications: dynamic(() => import("./TechnicalSpecifications")),


  three_d_model: dynamic(() => import("./ThreeDModel")),
  trumpet_video: dynamic(() => import("./TrumpetVideo")),
  youtube_video: dynamic(() => import("./YouTubeVideo")),
};
