// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";
import SmartValveBlogs from "./smartValveBlogs";
import SmartValveBlogsAdvanced from "./smartValveBlogsAdvanced";
import BlogGrid from "./blogGrid";

export const components = {
  content_artists: dynamic(() => import("./contentArtists")),
  home_artists: dynamic(() => import("./homeArtists")),
  bento_grid: dynamic(() => import("./bentoGrid")),
  blog_rich_text: dynamic(() => import("./blogRichText")),
  blog_image: dynamic(() => import("./blogImage")),
  blog_quote: dynamic(() => import("./blogQuote")),
  blog_cta: dynamic(() => import("./blogCta")),
  blog_related_posts: dynamic(() => import("./blogRelatedPosts")),
  blog_grid: BlogGrid,
  smart_valve_blogs: SmartValveBlogs,
  smart_valve_blogs_advanced: SmartValveBlogsAdvanced,

  content_contact: dynamic(() => import("./contentContact")),
  content: dynamic(() => import("./content")),

  smart_valve_optical_midi: dynamic(() => import("./smartValveOpticalMidi")),
  optical_midi: dynamic(() => import("./smartValveOpticalMidi")),
  feature_blocks: dynamic(() => import("./featureBlocks")),
  smart_valve_processor: dynamic(() => import("./smartValveProcessor")),
  smart_valve_transport: dynamic(() => import("./smartValveTransport")),
  modal_blocks: dynamic(() => import("./modalBlocks")),

  content_hero: dynamic(() => import("./contentHero")),
  smart_valve_pipe_animation: dynamic(() => import("./smartValvePipeAnimation")),
  home_choice: dynamic(() => import("./homeChoice")),
  smart_valve_landing: dynamic(() => import("./smartValveLanding")),
  home_landing: dynamic(() => import("./homeLanding")),
  smart_valve_video_hero: dynamic(() => import("./smartValveVideoHero")),
  smart_valve_image_hero: dynamic(() => import("./smartValveImageHero")),
  smart_valve_video: dynamic(() => import("./smartValveVideo")),


  smart_valve_possibilities: dynamic(() => import("./smartValvePossibilities")),
  product: dynamic(() => import("./product")),

  content_intro: dynamic(() => import("./contentIntro")),

  smart_valve_story: dynamic(() => import("./smartValveStory")),
  stylized_image: dynamic(() => import("./stylizedImage")),
  success: dynamic(() => import("./success")),

  smart_valve_tech_description: dynamic(() => import("./smartValveTechDescription")),
  valve_tech_description: dynamic(() => import("./smartValveTechDescription")),

  smart_valve_chest_3_d: dynamic(() => import("./smartValveChest3D")),
  smart_valve_chest: dynamic(() => import("./smartValveChest")),
  smart_valve_bento_grid: dynamic(() => import("./smartValveBentoGrid")),
  smart_valve_icon_blocks: dynamic(() => import("./smartValveIconBlocks")),
  smart_valve_quote: dynamic(() => import("./smartValveQuote")),
  smart_valve_endorsees: dynamic(() => import("./smartValveEndorsees")),

  instrument_header: dynamic(() => import("./instrumentHeader")),
  instrument_showcase: dynamic(() => import("./instrumentShowcase")),
  instrument_bento: dynamic(() => import("./instrumentBento")),
  instrument_feature: dynamic(() => import("./instrumentFeature")),
  instrument_split: dynamic(() => import("./instrumentSplit")),
  instrument_applications: dynamic(() => import("./instrumentApplications")),
  instrument_connectivity: dynamic(() => import("./instrumentConnectivity")),
  instrument_highlights: dynamic(() => import("./instrumentHighlights")),
  instrument_specs: dynamic(() => import("./instrumentSpecs")),
  instrument_faq: dynamic(() => import("./instrumentFaq")),
  instrument_cta: dynamic(() => import("./instrumentCta")),
  instrument_statement: dynamic(() => import("./instrumentStatement")),
  instrument_stats: dynamic(() => import("./instrumentStats")),
  instrument_gallery: dynamic(() => import("./instrumentGallery")),
  instrument_steps: dynamic(() => import("./instrumentSteps")),
  instrument_quote: dynamic(() => import("./instrumentQuote")),
  instrument_logos: dynamic(() => import("./instrumentLogos")),
  instrument_media_text: dynamic(() => import("./instrumentMediaText")),
  instrument_banner: dynamic(() => import("./instrumentBanner")),

  core_accessories: dynamic(() => import("./coreAccessories")),
  core_bento: dynamic(() => import("./coreBento")),
  core_demo_video: dynamic(() => import("./coreDemoVideo")),
  core_faq: dynamic(() => import("./coreFaq")),
  core_hero: dynamic(() => import("./coreHero")),
  core_specs: dynamic(() => import("./coreSpecs")),
  core_testimonial: dynamic(() => import("./coreTestimonial")),
  core_3_d: dynamic(() => import("./core3D")),
};
