// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  artists: dynamic(() => import("./Artists")),
  bento_grid: dynamic(() => import("./BentoGrid")),
  blog: dynamic(() => import("./Blog")),
  blog_listing: dynamic(() => import("./BlogListing")),
  blog_overview: dynamic(() => import("./BlogOverview")),
  contact_section: dynamic(() => import("./ContactSection")),
  content: dynamic(() => import("./Content")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  faq: dynamic(() => import("./FAQ")),
  feature: dynamic(() => import("./Feature")),
  grid_list: dynamic(() => import("./GridList")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  section_intro: dynamic(() => import("./SectionIntro")),
  stats: dynamic(() => import("./Stats")),
  testimonial: dynamic(() => import("./Testimonial")),
  three_d: dynamic(() => import("./ThreeD")),
};
